# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/ThomasSteinke/Projects/Voxel/builds

# Include any dependencies generated for this target.
include src/CMakeFiles/GLFW_303.dir/depend.make

# Include the progress variables for this target.
include src/CMakeFiles/GLFW_303.dir/progress.make

# Include the compile flags for this target's objects.
include src/CMakeFiles/GLFW_303.dir/flags.make

src/CMakeFiles/GLFW_303.dir/clipboard.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/clipboard.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/clipboard.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_1)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/clipboard.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/clipboard.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/clipboard.c

src/CMakeFiles/GLFW_303.dir/clipboard.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/clipboard.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/clipboard.c > CMakeFiles/GLFW_303.dir/clipboard.c.i

src/CMakeFiles/GLFW_303.dir/clipboard.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/clipboard.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/clipboard.c -o CMakeFiles/GLFW_303.dir/clipboard.c.s

src/CMakeFiles/GLFW_303.dir/clipboard.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/clipboard.c.o.requires

src/CMakeFiles/GLFW_303.dir/clipboard.c.o.provides: src/CMakeFiles/GLFW_303.dir/clipboard.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/clipboard.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/clipboard.c.o.provides

src/CMakeFiles/GLFW_303.dir/clipboard.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/clipboard.c.o

src/CMakeFiles/GLFW_303.dir/context.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/context.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/context.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_2)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/context.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/context.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/context.c

src/CMakeFiles/GLFW_303.dir/context.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/context.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/context.c > CMakeFiles/GLFW_303.dir/context.c.i

src/CMakeFiles/GLFW_303.dir/context.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/context.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/context.c -o CMakeFiles/GLFW_303.dir/context.c.s

src/CMakeFiles/GLFW_303.dir/context.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/context.c.o.requires

src/CMakeFiles/GLFW_303.dir/context.c.o.provides: src/CMakeFiles/GLFW_303.dir/context.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/context.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/context.c.o.provides

src/CMakeFiles/GLFW_303.dir/context.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/context.c.o

src/CMakeFiles/GLFW_303.dir/gamma.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/gamma.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/gamma.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_3)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/gamma.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/gamma.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/gamma.c

src/CMakeFiles/GLFW_303.dir/gamma.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/gamma.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/gamma.c > CMakeFiles/GLFW_303.dir/gamma.c.i

src/CMakeFiles/GLFW_303.dir/gamma.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/gamma.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/gamma.c -o CMakeFiles/GLFW_303.dir/gamma.c.s

src/CMakeFiles/GLFW_303.dir/gamma.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/gamma.c.o.requires

src/CMakeFiles/GLFW_303.dir/gamma.c.o.provides: src/CMakeFiles/GLFW_303.dir/gamma.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/gamma.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/gamma.c.o.provides

src/CMakeFiles/GLFW_303.dir/gamma.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/gamma.c.o

src/CMakeFiles/GLFW_303.dir/init.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/init.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/init.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_4)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/init.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/init.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/init.c

src/CMakeFiles/GLFW_303.dir/init.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/init.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/init.c > CMakeFiles/GLFW_303.dir/init.c.i

src/CMakeFiles/GLFW_303.dir/init.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/init.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/init.c -o CMakeFiles/GLFW_303.dir/init.c.s

src/CMakeFiles/GLFW_303.dir/init.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/init.c.o.requires

src/CMakeFiles/GLFW_303.dir/init.c.o.provides: src/CMakeFiles/GLFW_303.dir/init.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/init.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/init.c.o.provides

src/CMakeFiles/GLFW_303.dir/init.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/init.c.o

src/CMakeFiles/GLFW_303.dir/input.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/input.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/input.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_5)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/input.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/input.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/input.c

src/CMakeFiles/GLFW_303.dir/input.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/input.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/input.c > CMakeFiles/GLFW_303.dir/input.c.i

src/CMakeFiles/GLFW_303.dir/input.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/input.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/input.c -o CMakeFiles/GLFW_303.dir/input.c.s

src/CMakeFiles/GLFW_303.dir/input.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/input.c.o.requires

src/CMakeFiles/GLFW_303.dir/input.c.o.provides: src/CMakeFiles/GLFW_303.dir/input.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/input.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/input.c.o.provides

src/CMakeFiles/GLFW_303.dir/input.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/input.c.o

src/CMakeFiles/GLFW_303.dir/joystick.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/joystick.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/joystick.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_6)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/joystick.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/joystick.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/joystick.c

src/CMakeFiles/GLFW_303.dir/joystick.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/joystick.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/joystick.c > CMakeFiles/GLFW_303.dir/joystick.c.i

src/CMakeFiles/GLFW_303.dir/joystick.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/joystick.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/joystick.c -o CMakeFiles/GLFW_303.dir/joystick.c.s

src/CMakeFiles/GLFW_303.dir/joystick.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/joystick.c.o.requires

src/CMakeFiles/GLFW_303.dir/joystick.c.o.provides: src/CMakeFiles/GLFW_303.dir/joystick.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/joystick.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/joystick.c.o.provides

src/CMakeFiles/GLFW_303.dir/joystick.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/joystick.c.o

src/CMakeFiles/GLFW_303.dir/monitor.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/monitor.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/monitor.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_7)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/monitor.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/monitor.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/monitor.c

src/CMakeFiles/GLFW_303.dir/monitor.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/monitor.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/monitor.c > CMakeFiles/GLFW_303.dir/monitor.c.i

src/CMakeFiles/GLFW_303.dir/monitor.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/monitor.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/monitor.c -o CMakeFiles/GLFW_303.dir/monitor.c.s

src/CMakeFiles/GLFW_303.dir/monitor.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/monitor.c.o.requires

src/CMakeFiles/GLFW_303.dir/monitor.c.o.provides: src/CMakeFiles/GLFW_303.dir/monitor.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/monitor.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/monitor.c.o.provides

src/CMakeFiles/GLFW_303.dir/monitor.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/monitor.c.o

src/CMakeFiles/GLFW_303.dir/time.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/time.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/time.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_8)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/time.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/time.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/time.c

src/CMakeFiles/GLFW_303.dir/time.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/time.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/time.c > CMakeFiles/GLFW_303.dir/time.c.i

src/CMakeFiles/GLFW_303.dir/time.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/time.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/time.c -o CMakeFiles/GLFW_303.dir/time.c.s

src/CMakeFiles/GLFW_303.dir/time.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/time.c.o.requires

src/CMakeFiles/GLFW_303.dir/time.c.o.provides: src/CMakeFiles/GLFW_303.dir/time.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/time.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/time.c.o.provides

src/CMakeFiles/GLFW_303.dir/time.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/time.c.o

src/CMakeFiles/GLFW_303.dir/window.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/window.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/window.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_9)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/window.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/window.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/window.c

src/CMakeFiles/GLFW_303.dir/window.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/window.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/window.c > CMakeFiles/GLFW_303.dir/window.c.i

src/CMakeFiles/GLFW_303.dir/window.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/window.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/window.c -o CMakeFiles/GLFW_303.dir/window.c.s

src/CMakeFiles/GLFW_303.dir/window.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/window.c.o.requires

src/CMakeFiles/GLFW_303.dir/window.c.o.provides: src/CMakeFiles/GLFW_303.dir/window.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/window.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/window.c.o.provides

src/CMakeFiles/GLFW_303.dir/window.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/window.c.o

src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_clipboard.m
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_10)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_clipboard.m

src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_clipboard.m > CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.i

src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_clipboard.m -o CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.s

src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o.requires

src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o.provides: src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o.provides

src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o.provides.build: src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o

src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_gamma.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_11)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_gamma.c

src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/cocoa_gamma.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_gamma.c > CMakeFiles/GLFW_303.dir/cocoa_gamma.c.i

src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/cocoa_gamma.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_gamma.c -o CMakeFiles/GLFW_303.dir/cocoa_gamma.c.s

src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o.requires

src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o.provides: src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o.provides

src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o

src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_init.m
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_12)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/cocoa_init.m.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_init.m

src/CMakeFiles/GLFW_303.dir/cocoa_init.m.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/cocoa_init.m.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_init.m > CMakeFiles/GLFW_303.dir/cocoa_init.m.i

src/CMakeFiles/GLFW_303.dir/cocoa_init.m.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/cocoa_init.m.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_init.m -o CMakeFiles/GLFW_303.dir/cocoa_init.m.s

src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o.requires

src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o.provides: src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o.provides

src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o.provides.build: src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o

src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_joystick.m
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_13)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_joystick.m

src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/cocoa_joystick.m.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_joystick.m > CMakeFiles/GLFW_303.dir/cocoa_joystick.m.i

src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/cocoa_joystick.m.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_joystick.m -o CMakeFiles/GLFW_303.dir/cocoa_joystick.m.s

src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o.requires

src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o.provides: src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o.provides

src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o.provides.build: src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o

src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_monitor.m
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_14)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_monitor.m

src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/cocoa_monitor.m.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_monitor.m > CMakeFiles/GLFW_303.dir/cocoa_monitor.m.i

src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/cocoa_monitor.m.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_monitor.m -o CMakeFiles/GLFW_303.dir/cocoa_monitor.m.s

src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o.requires

src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o.provides: src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o.provides

src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o.provides.build: src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o

src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_time.c
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_15)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/cocoa_time.c.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_time.c

src/CMakeFiles/GLFW_303.dir/cocoa_time.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/cocoa_time.c.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_time.c > CMakeFiles/GLFW_303.dir/cocoa_time.c.i

src/CMakeFiles/GLFW_303.dir/cocoa_time.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/cocoa_time.c.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_time.c -o CMakeFiles/GLFW_303.dir/cocoa_time.c.s

src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o.requires

src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o.provides: src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o.provides

src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o.provides.build: src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o

src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_window.m
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_16)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/cocoa_window.m.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_window.m

src/CMakeFiles/GLFW_303.dir/cocoa_window.m.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/cocoa_window.m.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_window.m > CMakeFiles/GLFW_303.dir/cocoa_window.m.i

src/CMakeFiles/GLFW_303.dir/cocoa_window.m.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/cocoa_window.m.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/cocoa_window.m -o CMakeFiles/GLFW_303.dir/cocoa_window.m.s

src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o.requires

src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o.provides: src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o.provides

src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o.provides.build: src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o

src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o: src/CMakeFiles/GLFW_303.dir/flags.make
src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o: /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/nsgl_context.m
	$(CMAKE_COMMAND) -E cmake_progress_report /Users/ThomasSteinke/Projects/Voxel/builds/CMakeFiles $(CMAKE_PROGRESS_17)
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Building C object src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -o CMakeFiles/GLFW_303.dir/nsgl_context.m.o   -c /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/nsgl_context.m

src/CMakeFiles/GLFW_303.dir/nsgl_context.m.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/GLFW_303.dir/nsgl_context.m.i"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -E /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/nsgl_context.m > CMakeFiles/GLFW_303.dir/nsgl_context.m.i

src/CMakeFiles/GLFW_303.dir/nsgl_context.m.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/GLFW_303.dir/nsgl_context.m.s"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && /usr/bin/cc  $(C_DEFINES) $(C_FLAGS) -S /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src/nsgl_context.m -o CMakeFiles/GLFW_303.dir/nsgl_context.m.s

src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o.requires:
.PHONY : src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o.requires

src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o.provides: src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o.requires
	$(MAKE) -f src/CMakeFiles/GLFW_303.dir/build.make src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o.provides.build
.PHONY : src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o.provides

src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o.provides.build: src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o

# Object files for target GLFW_303
GLFW_303_OBJECTS = \
"CMakeFiles/GLFW_303.dir/clipboard.c.o" \
"CMakeFiles/GLFW_303.dir/context.c.o" \
"CMakeFiles/GLFW_303.dir/gamma.c.o" \
"CMakeFiles/GLFW_303.dir/init.c.o" \
"CMakeFiles/GLFW_303.dir/input.c.o" \
"CMakeFiles/GLFW_303.dir/joystick.c.o" \
"CMakeFiles/GLFW_303.dir/monitor.c.o" \
"CMakeFiles/GLFW_303.dir/time.c.o" \
"CMakeFiles/GLFW_303.dir/window.c.o" \
"CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o" \
"CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o" \
"CMakeFiles/GLFW_303.dir/cocoa_init.m.o" \
"CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o" \
"CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o" \
"CMakeFiles/GLFW_303.dir/cocoa_time.c.o" \
"CMakeFiles/GLFW_303.dir/cocoa_window.m.o" \
"CMakeFiles/GLFW_303.dir/nsgl_context.m.o"

# External object files for target GLFW_303
GLFW_303_EXTERNAL_OBJECTS =

src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/clipboard.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/context.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/gamma.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/init.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/input.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/joystick.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/monitor.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/time.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/window.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/build.make
src/libglfw3.a: src/CMakeFiles/GLFW_303.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --red --bold "Linking C static library libglfw3.a"
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && $(CMAKE_COMMAND) -P CMakeFiles/GLFW_303.dir/cmake_clean_target.cmake
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && $(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/GLFW_303.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
src/CMakeFiles/GLFW_303.dir/build: src/libglfw3.a
.PHONY : src/CMakeFiles/GLFW_303.dir/build

src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/clipboard.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/context.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/gamma.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/init.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/input.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/joystick.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/monitor.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/time.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/window.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/cocoa_clipboard.m.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/cocoa_gamma.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/cocoa_init.m.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/cocoa_joystick.m.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/cocoa_monitor.m.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/cocoa_time.c.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/cocoa_window.m.o.requires
src/CMakeFiles/GLFW_303.dir/requires: src/CMakeFiles/GLFW_303.dir/nsgl_context.m.o.requires
.PHONY : src/CMakeFiles/GLFW_303.dir/requires

src/CMakeFiles/GLFW_303.dir/clean:
	cd /Users/ThomasSteinke/Projects/Voxel/builds/src && $(CMAKE_COMMAND) -P CMakeFiles/GLFW_303.dir/cmake_clean.cmake
.PHONY : src/CMakeFiles/GLFW_303.dir/clean

src/CMakeFiles/GLFW_303.dir/depend:
	cd /Users/ThomasSteinke/Projects/Voxel/builds && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3 /Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src /Users/ThomasSteinke/Projects/Voxel/builds /Users/ThomasSteinke/Projects/Voxel/builds/src /Users/ThomasSteinke/Projects/Voxel/builds/src/CMakeFiles/GLFW_303.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : src/CMakeFiles/GLFW_303.dir/depend

