# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# compile C with /usr/bin/cc
C_FLAGS =  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -I/Users/ThomasSteinke/Projects/Voxel/external/glfw-3.0.3/src -I/Users/ThomasSteinke/Projects/Voxel/builds/src    -Wall

C_DEFINES = 

